apiVersion: v1
kind: Service
metadata:
  name: ollama-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ollama
  ports:
    - name: ollama
      protocol: TCP
      port: 11434
      targetPort: 11434
      nodePort: 30347